apiVersion: 1

datasources:
  - name: InfluxDB-Telecom
    uid: influxdb-telecom
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: telecom
      defaultBucket: telecom_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
